# This is a basic workflow to help you get started with Actions

name: 🧪 test

# Controls when the action will run. 
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: setup node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x

      - name: checkout
        uses: actions/checkout@master

      - name: install
        run: npm install
        
      - name: plugins
        run: npm install umi-plugin-antd-theme umi-plugin-pro

      - name: lint
        run: npm run lint
        
      - name: tsc
        run: npm run tsc
        
      - name: build
        run: npm run build
      
      - name: test
        run: npm run test:all
        env:
          CI: true
          PROGRESS: none
          NODE_ENV: test
          NODE_OPTIONS: --max_old_space_size=4096
