# This is a basic workflow to help you get started with Actions

name: 🧪 test

# Controls when the action will run. 
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: create package-lock.json
        run: npm i --package-lock-only
        
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        
      - name: install
        run: npm ci

      - name: start
        run: npm run start
        
      - name: test
        run: npm test -- -w 1 --coverage

      - name: coverage
        run: bash <(curl -s https://codecov.io/bash)
    needs: setup
